### PR TITLE
#509 move documentation to right links.

### PR DESCRIPTION
**Pull request by davetcc**

### CODE REVIEW

**Review by vzahradnik — CHANGES_REQUESTED** [review]
Hmm... looks good but the tests are failing. Before merging, we should make sure they run fine.

**Comment by davetcc** [comment]
> Hmm... looks good but the tests are failing. Before merging, we should make sure they run fine.

Yes, fixing them now. Plan is to do a release later today to fix up everything post the move. There are few changes and they've all been tested already, so I'll release it as a patch 4.3.1

**Comment by vzahradnik** [comment]
Ok then. I will approve this one.

**Comment by davetcc** [comment]
I've tested most of the URLs manually BTW, not every single one but the vast majority

**Review by vzahradnik — APPROVED** [review]

**Pull request merged**
